
import { ThemeProvider } from "@/components/theme-provider"

import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subset: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          ></ThemeProvider>
        {children}
      </body>
    </html>
  );
}
